version: '2'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && gem install bundler -v 1.17.3 && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - bundle:/bundle
      - ${APP_VOLUME}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./dockerdata/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"
volumes:
  bundle: